extends:
  - next/core-web-vitals
  - prettier
ignorePatterns:
  - node_modules
rules:
  "semi":
    - error
    - always
overrides:
  - files:
      - "**/*.ts?(x)"
    parserOptions:
      project: tsconfig.json
      tsConfigRootDir: __dirname
      sourceType: module
    extends:
      - next/core-web-vitals
      - plugin:@typescript-eslint/recommended
      - prettier
    plugins:
      - "@typescript-eslint"
