plugins: [prettier-plugin-solidity]
useTabs: false
trailingComma: none
tabWidth: 2
semi: true
singleQuote: true
bracketSpacing: true
printWidth: 120
overrides:
  - files: "*.sol"
    options:
      tabWidth: 4
      singleQuote: false
      bracketSpacing: false
  - files: "*.y(*)ml"
    options:
      singleQuote: false
